name: Build Android APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.15.0'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build Web Project
        run: npm run build

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Sync Capacitor
        run: |
          npx cap sync android

      - name: Build Android APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Prepare APK for signing
        run: |
          mkdir -p android/app/build/outputs/apk/to_sign
          cp android/app/build/outputs/apk/release/app-release-unsigned.apk android/app/build/outputs/apk/to_sign/app-unsigned.apk

     # - name: Locate APK
       # run: find android/app/build/outputs/apk -name "*.apk"

      - name: Sign App Bundle
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: android/app/build/outputs/apk/to_sign
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: matrixtinz-release
          path: ${{ steps.sign_app.outputs.signedReleaseFile }}
